# Generated by Django 5.1.2 on 2024-10-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=150)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=128)),
            ],
            options={
                'db_table': 'users',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_column='company_id', default=None, null=True)),
                ('name', models.CharField(db_column='name', max_length=100, null=True)),
                ('domain', models.CharField(db_column='domain', max_length=200, null=True)),
                ('year_founded', models.IntegerField(db_column='year_founded', null=True)),
                ('industry', models.CharField(db_column='industry', max_length=200, null=True)),
                ('size_range', models.CharField(db_column='size_range', max_length=200, null=True)),
                ('locality', models.CharField(db_column='locality', max_length=500, null=True)),
                ('country', models.CharField(db_column='country', max_length=100, null=True)),
                ('linkedin_url', models.CharField(db_column='linkedin_url', max_length=500, null=True)),
                ('current_emp_est', models.IntegerField(db_column='current_emp_est', null=True)),
                ('total_emp_est', models.IntegerField(db_column='total_emp_est', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
                ('userid', models.ForeignKey(db_column='userid', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalyst_app.users')),
            ],
            options={
                'db_table': 'company',
                'ordering': ('-id',),
            },
        ),
    ]
