# Generated by Django 5.1.2 on 2024-10-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_app', '0002_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='company_id', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, db_column='country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_emp_est',
            field=models.IntegerField(blank=True, db_column='current_emp_est', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, db_column='domain', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, db_column='industry', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_url',
            field=models.CharField(blank=True, db_column='linkedin_url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='locality',
            field=models.CharField(blank=True, db_column='locality', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='size_range',
            field=models.CharField(blank=True, db_column='size_range', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_emp_est',
            field=models.IntegerField(blank=True, db_column='total_emp_est', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.IntegerField(blank=True, db_column='year_founded', null=True),
        ),
    ]
