# Generated by Django 5.1.2 on 2024-10-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_app', '0003_alter_company_company_id_alter_company_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, db_column='file_name', max_length=100, null=True)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=200, null=True)),
                ('total_count', models.IntegerField(blank=True, db_column='total_count', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', null=True)),
            ],
            options={
                'db_table': 'company_summary',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='users',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='created_date', null=True),
        ),
    ]
