# Generated by Django 5.1.2 on 2024-10-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_app', '0004_company_summary_users_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_date',
        ),
    ]
