# Generated by Django 5.1.2 on 2024-10-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_app', '0005_remove_company_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='created_date', null=True),
        ),
    ]
