# Generated by Django 5.1.2 on 2024-10-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_app', '0007_remove_users_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_summary',
        ),
    ]
